/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: divert.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "divert.pb-c.h"
void   divert_message__init
                     (DivertMessage         *message)
{
  static const DivertMessage init_value = DIVERT_MESSAGE__INIT;
  *message = init_value;
}
size_t divert_message__get_packed_size
                     (const DivertMessage *message)
{
  assert(message->base.descriptor == &divert_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t divert_message__pack
                     (const DivertMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &divert_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t divert_message__pack_to_buffer
                     (const DivertMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &divert_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DivertMessage *
       divert_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DivertMessage *)
     protobuf_c_message_unpack (&divert_message__descriptor,
                                allocator, len, data);
}
void   divert_message__free_unpacked
                     (DivertMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &divert_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor divert_message__field_descriptors[4] =
{
  {
    "src_port",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DivertMessage, has_src_port),
    offsetof(DivertMessage, src_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_port",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DivertMessage, has_dst_port),
    offsetof(DivertMessage, dst_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_host",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DivertMessage, src_host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_host",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DivertMessage, dst_host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned divert_message__field_indices_by_name[] = {
  3,   /* field[3] = dst_host */
  1,   /* field[1] = dst_port */
  2,   /* field[2] = src_host */
  0,   /* field[0] = src_port */
};
static const ProtobufCIntRange divert_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor divert_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DivertMessage",
  "DivertMessage",
  "DivertMessage",
  "",
  sizeof(DivertMessage),
  4,
  divert_message__field_descriptors,
  divert_message__field_indices_by_name,
  1,  divert_message__number_ranges,
  (ProtobufCMessageInit) divert_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
