// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: divert.proto

#include "divert.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR DivertMessage::DivertMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.src_host_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.dest_host_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.src_port_)*/0
  , /*decltype(_impl_.dest_port_)*/0} {}
struct DivertMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DivertMessageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DivertMessageDefaultTypeInternal() {}
  union {
    DivertMessage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DivertMessageDefaultTypeInternal _DivertMessage_default_instance_;
static ::_pb::Metadata file_level_metadata_divert_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_divert_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_divert_2eproto = nullptr;

const uint32_t TableStruct_divert_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::DivertMessage, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::DivertMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DivertMessage, _impl_.src_port_),
  PROTOBUF_FIELD_OFFSET(::DivertMessage, _impl_.dest_port_),
  PROTOBUF_FIELD_OFFSET(::DivertMessage, _impl_.src_host_),
  PROTOBUF_FIELD_OFFSET(::DivertMessage, _impl_.dest_host_),
  2,
  3,
  0,
  1,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, -1, sizeof(::DivertMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_DivertMessage_default_instance_._instance,
};

const char descriptor_table_protodef_divert_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014divert.proto\"Y\n\rDivertMessage\022\020\n\010src_p"
  "ort\030\001 \001(\005\022\021\n\tdest_port\030\002 \001(\005\022\020\n\010src_host"
  "\030\003 \001(\t\022\021\n\tdest_host\030\004 \001(\t"
  ;
static ::_pbi::once_flag descriptor_table_divert_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_divert_2eproto = {
    false, false, 105, descriptor_table_protodef_divert_2eproto,
    "divert.proto",
    &descriptor_table_divert_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_divert_2eproto::offsets,
    file_level_metadata_divert_2eproto, file_level_enum_descriptors_divert_2eproto,
    file_level_service_descriptors_divert_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_divert_2eproto_getter() {
  return &descriptor_table_divert_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_divert_2eproto(&descriptor_table_divert_2eproto);

// ===================================================================

class DivertMessage::_Internal {
 public:
  using HasBits = decltype(std::declval<DivertMessage>()._impl_._has_bits_);
  static void set_has_src_port(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_dest_port(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_src_host(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_dest_host(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

DivertMessage::DivertMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DivertMessage)
}
DivertMessage::DivertMessage(const DivertMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DivertMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.src_host_){}
    , decltype(_impl_.dest_host_){}
    , decltype(_impl_.src_port_){}
    , decltype(_impl_.dest_port_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.src_host_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.src_host_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_src_host()) {
    _this->_impl_.src_host_.Set(from._internal_src_host(), 
      _this->GetArenaForAllocation());
  }
  _impl_.dest_host_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dest_host_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_dest_host()) {
    _this->_impl_.dest_host_.Set(from._internal_dest_host(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.src_port_, &from._impl_.src_port_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.dest_port_) -
    reinterpret_cast<char*>(&_impl_.src_port_)) + sizeof(_impl_.dest_port_));
  // @@protoc_insertion_point(copy_constructor:DivertMessage)
}

inline void DivertMessage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.src_host_){}
    , decltype(_impl_.dest_host_){}
    , decltype(_impl_.src_port_){0}
    , decltype(_impl_.dest_port_){0}
  };
  _impl_.src_host_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.src_host_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.dest_host_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.dest_host_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DivertMessage::~DivertMessage() {
  // @@protoc_insertion_point(destructor:DivertMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DivertMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.src_host_.Destroy();
  _impl_.dest_host_.Destroy();
}

void DivertMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DivertMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:DivertMessage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.src_host_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.dest_host_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x0000000cu) {
    ::memset(&_impl_.src_port_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.dest_port_) -
        reinterpret_cast<char*>(&_impl_.src_port_)) + sizeof(_impl_.dest_port_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DivertMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 src_port = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_src_port(&has_bits);
          _impl_.src_port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 dest_port = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_dest_port(&has_bits);
          _impl_.dest_port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string src_host = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_src_host();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "DivertMessage.src_host");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      // optional string dest_host = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_dest_host();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "DivertMessage.dest_host");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DivertMessage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DivertMessage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 src_port = 1;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_src_port(), target);
  }

  // optional int32 dest_port = 2;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_dest_port(), target);
  }

  // optional string src_host = 3;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_src_host().data(), static_cast<int>(this->_internal_src_host().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "DivertMessage.src_host");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_src_host(), target);
  }

  // optional string dest_host = 4;
  if (cached_has_bits & 0x00000002u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_dest_host().data(), static_cast<int>(this->_internal_dest_host().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "DivertMessage.dest_host");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_dest_host(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DivertMessage)
  return target;
}

size_t DivertMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DivertMessage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    // optional string src_host = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_src_host());
    }

    // optional string dest_host = 4;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_dest_host());
    }

    // optional int32 src_port = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_src_port());
    }

    // optional int32 dest_port = 2;
    if (cached_has_bits & 0x00000008u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_dest_port());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DivertMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DivertMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DivertMessage::GetClassData() const { return &_class_data_; }


void DivertMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DivertMessage*>(&to_msg);
  auto& from = static_cast<const DivertMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DivertMessage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_src_host(from._internal_src_host());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_dest_host(from._internal_dest_host());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.src_port_ = from._impl_.src_port_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.dest_port_ = from._impl_.dest_port_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DivertMessage::CopyFrom(const DivertMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DivertMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DivertMessage::IsInitialized() const {
  return true;
}

void DivertMessage::InternalSwap(DivertMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.src_host_, lhs_arena,
      &other->_impl_.src_host_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.dest_host_, lhs_arena,
      &other->_impl_.dest_host_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DivertMessage, _impl_.dest_port_)
      + sizeof(DivertMessage::_impl_.dest_port_)
      - PROTOBUF_FIELD_OFFSET(DivertMessage, _impl_.src_port_)>(
          reinterpret_cast<char*>(&_impl_.src_port_),
          reinterpret_cast<char*>(&other->_impl_.src_port_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DivertMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_divert_2eproto_getter, &descriptor_table_divert_2eproto_once,
      file_level_metadata_divert_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::DivertMessage*
Arena::CreateMaybeMessage< ::DivertMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DivertMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
